#!/bin/bash
<!-- Device trees -->
git clone https://github.com/Notkerd69/device_xiaomi_fog-1 -b rizen device/xiaomi/fog
git clone https://github.com/dblenk-project/device_xiaomi_fog-kernel -b 13 device/xiaomi/fog-kernel
git clone https://github.com/Notkerd69/device_xiaomi_sm6225-common-1 -b thirteen device/xiaomi/sm6225-common
git clone https://github.com/Vhmit/kernel_xiaomi_fog -b master kernel/xiaomi/sm6225
git clone https://github.com/Notkerd69/proprietary_vendor_xiaomi_fog -b thirteen vendor/xiaomi/fog

<!-- Vendor Blobs -->
git clone https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_qcom_common vendor/qcom/common
git clone https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_sm6225-common android/vendor-blobs/vendor_xiaomi_sm6225-common

<!-- QCOM COMMON Dependencies -->
git clone https://github.com/PixelExperience-Devices/device_qcom_common -b thirteen device/qcom/common
git clone https://github.com/PixelExperience-Devices/device_qcom_common-sepolicy -b thirteen device/qcom/common-sepolicy
git clone https://github.com/PixelExperience-Devices/device_qcom_qssi -b thirteen device/qcom/qssi
git clone https://github.com/PixelExperience-Devices/device_qcom_vendor-common -b thirteen device/qcom/vendor-common
git clone https://github.com/PixelExperience-Devices/device_qcom_wlan -b thirteen device/qcom/wlan
git clone https://github.com/PixelExperience-Devices/device_qcom_wlan -b thirteen device/qcom/wlan
git clone https://github.com/PixelExperience/vendor_qcom_opensource_commonsys-intf_bluetooth -b thirteen vendor/qcom/opensource/commonsys-intf/bluetooth
git clone https://github.com/PixelExperience/vendor_qcom_opensource_core-utils -b thirteen vendor/qcom/opensource/core-utils
git clone https://github.com/PixelExperience/vendor_qcom_opensource_commonsys_dpm -b thirteen vendor/qcom/opensource/commonsys/dpm

<!-- Bengal HALs -->
git clone https://github.com/PixelExperience/hardware_qcom-caf_bengal_audio -b thirteen hardware/qcom-caf/bengal/audio
git clone https://github.com/PixelExperience/hardware_qcom-caf_bengal_display -b thirteen hardware/qcom-caf/bengal/display
git clone https://github.com/PixelExperience/hardware_qcom-caf_bengal_gps -b thirteen hardware/qcom-caf/bengal/gps
git clone https://github.com/PixelExperience/hardware_qcom-caf_bengal_media -b thirteen hardware/qcom-caf/bengal/media

<!-- Pro clag -->
git clone https://github.com/kdrag0n/proton-clang -b master prebuilts/clang/host/linux-x86/clang-proton
